# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: swift
podfile: Example/Podfile
before_install:
- gem install cocoapods 
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Juggernaut.xcworkspace -scheme Juggernaut-Example -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
